### ISSUE TITLE
Emoji showing blank spaces

### ISSUE THREAD

**Issue by chagai95** [igniterealtime/openfire-pade-plugin#327] opened 2021-05-01 21:28 UTC
![image](https://user-images.githubusercontent.com/31655082/116795396-dfd50380-aad4-11eb-898c-44964f716c03.png)

**Comment by deleolajide** [comment] 2021-05-04 09:03
I can't reproduce this. It could be your browser cache

**Comment by gjaekel** [comment] 2021-05-04 09:08
@chagai95 faced this issue on my installation. It's probably an UTF-8 issue at my platform, concerning the database or something like that. I'll investigate this by defining the Emoji-Set on the config_custom.js

**Comment by deleolajide** [comment] 2021-05-22 18:50
I can't reproduce this. Closing for now

**Closed by deleolajide** 2021-05-22 18:50 UTC
