### ISSUE TITLE
Dominant Speaker Switching don't work

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#120] opened 2020-12-04 11:16 UTC
With the current V1.1, the *Dominant Speaker Switching* mechanism seems to be out of order.

In contrast to using other servers (like https://meet.ffmuc.net), I can't see any messages according this feature in the websocket traffic section, neither on the XMPP control connection nor on the colibri connection.

**Comment by gjaekel** [comment] 2020-12-07 06:44
Compare also your screenshot for V1.1.3! (https://user-images.githubusercontent.com/19855721/101318001-e3cf6300-385f-11eb-9ebd-ce1aa813b0df.png)

**Comment by ClaudeStabile** [comment] 2020-12-07 11:47
I also have same issue with dominant speaker speaker at www.free-solutions.org with OF 1.1.2 while it works with pure Jitsi. One config parameter differ ?

**Comment by gjaekel** [comment] 2020-12-07 17:50
At the moment, using datachannels instead of websockets for client communication will bring back the *Dominant Speaker Switching*.

**Comment by ClaudeStabile** [comment] 2020-12-07 18:20
@gjaekel can you pls specify what you did exactly ? Untick websocker in meeting/settings via console ?

**Comment by gjaekel** [comment] 2020-12-07 18:26
There's a new V1.1.3@20201207-17000 which offers this as a option inside the GUI.

I don't installed this yet, I was patching the servlet providing the ` /config.js` by myself. I did a quick test with this and two other co-workers and it was working with thins.

**Comment by ClaudeStabile** [comment] 2020-12-07 18:46
I have untick websocket but apparently does not work for dominant speaker. Did you enable a variable in your config.js ? which one

@deleolajide what do you recommend websocket ticked or not ?
Could this influence the dominant speaker behaviour ?

![screenshot3](https://user-images.githubusercontent.com/29485972/101391449-9b965c00-38c4-11eb-9a18-b9a087bc4856.png)

**Comment by deleolajide** [comment] 2020-12-07 21:14
Networking...
![image](https://user-images.githubusercontent.com/110731/101406234-14031a00-38d1-11eb-83bd-95bba7298e09.png)

**Comment by ClaudeStabile** [comment] 2020-12-07 21:56
Perfect thx !

**Comment by naive924** [comment] 2020-12-19 13:00
@deleolajide @gjaekel 
The reason why Dominant Speaker does not switch is that colibiri-ws websockets is not set correctly.
```
[Jetty-QTP-BOSH-103]: ProxyConnection -  ProxyConnection  ws://localhost:8080/colibri-ws/default-id/4b8a8110b218948f/e5139d33?pwd=3cbl1ieh0talqj3b8adcrnst0i null
[HttpClient@3c5d948-124]: ProxyConnection - Error: Failed to upgrade to websocket: Unexpected HTTP Response Status Code:  404 Not Found
```
* As @gjaekel pointed out, I was able to figure it out.

The setting to proxy colibiri-ws seems to require a public port.
* see https://github.com/jitsi/jitsi-videobridge/blob/master/doc/web-sockets.md

Also, 8080 seems to overlap with jetty's default.
With this fix, it will also be fixed in datachannels websocket.

![image](https://user-images.githubusercontent.com/6185430/102689849-ce394080-4244-11eb-9c66-451da135f0b3.png)
![image](https://user-images.githubusercontent.com/6185430/102689856-d72a1200-4244-11eb-81d4-efb543a0abac.png)

**Comment by naive924** [comment] 2020-12-19 13:23
The current version seems to only be able to send colibiri-ws websockets.
https://github.com/igniterealtime/openfire-pade-plugin/issues/119#issuecomment-739970922

Also, Windows must be datachannels websocket.
https://github.com/igniterealtime/openfire-pade-plugin/issues/119#issuecomment-740013878

**Comment by gjaekel** [comment] 2020-12-19 13:52
>Also, 8080 seems to overlap with jetty's default.
>With this fix, it will also be fixed in datachannels websocket.

Dear Neive,
you probably misunderstand the concepts Dele want to reach: Minimize the number of  public ports need to run the software. The OFMeet plugin already offers a websocket proxy (at `/ws`) used by the _Jitsi Meet_ controll connection. And now, he implement a second one (at ` /colibri-ws` ) to support the websocket mode of the new bridge and focus.
In this code, we still have an issue preventing the proper http(s) upgrade to ws(s) or something like that. This issue will prevent the focus to work and as a consequence, the video quality to rise up from the low resulution at start.

Sorry, but tThe change you propose will work from a technical point of view, but don't server the aim we want to reach.

**Comment by deleolajide** [comment] 2020-12-19 15:26
> Sorry, but the change you propose will work from a technical point of view, but don't server the aim we want to reach. I'm persuaded that we'll able to trace down the bug and fix the code in the way Dele want to achieve.

@gjaekel is correct. @naive924, your [PR](https://github.com/igniterealtime/openfire-pade-plugin/pull/164) does not fix the 404 error which could be or not even connected with why dominant speaker is not working. Can you please confirm that your PR actually fixes the dominant speaker issue for you in both Windows and Linux and does not break anything else?

As far as I know JVB uses 8080 by default for http and websockets. Confirmation of that is the meeting summary which does a REST request to JVB on ports 8080. when I have time, I will look into the  404 error, but I don't think it is causing the Dominant Speaker Switching error. I think that is coming upstream from Jitsi code and may not work for Windows until they fix it.

**Comment by naive924** [comment] 2020-12-19 15:55
Hi, @deleolajide @gjaekel
Sorry. Please use pull req for reference only.

- If openfire.script records ofmeet.websockets.plainport as 8080, pull req will be ignored.
- Linux has not been confirmed yet. It may take some time.
  - Analyzing ColibriWebSocketServlet seems to take some time. https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/java/org/jitsi/videobridge/websocket/ColibriWebSocketServlet.java#L28
- This is the correct behavior of colibri-ws.
![image](https://user-images.githubusercontent.com/6185430/102693378-88d53d00-425d-11eb-9cea-f708e51df3da.png)

**Comment by deleolajide** [comment] 2020-12-19 18:13
@naive924 thanks for the investigative work and additional information you have provided on proxy access to solve this issue 👍 

My proxy needs more work to correctly send the dominant speaker information required. If you can open multiple ports, then ignore my proxy and expose port 8443 to your browser users. Make sure you set the public port to 8443. That could work provided the browser accepts Openfire's TLS certificate to open a connection from Jitsi Meet to JVB on port 8443. 

I could not test this as my dev PC is Windows and I used localhost for testing. My public server runs on Linux and I only have port 443 open, so I had to use datachannel instead.

**Comment by naive924** [comment] 2020-12-19 18:28
Thank you for your continued support 👍

**Comment by gjaekel** [comment] 2020-12-19 20:24
I just verify the actual firewall settings (using nmap) I requested at our network fellow. I can't change anything of this rules next days, but it turns out that I had pleased him to "open" (i.e. a static NAT)  a port for the OpenFire XMPP filetransfer service at eval stage. I may disable this service at Openfire and temporary use this port for the JVBs wss listener for further investigations on Linux, too.

**Comment by gjaekel** [comment] 2020-12-19 20:51
> Analyzing ColibriWebSocketServlet seems to take some time. 

There are tree different possibilities to end with a `404`. At first I think we have to enable the logger.
https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/java/org/jitsi/videobridge/websocket/ColibriWebSocketServlet.java#L28-L59

**Comment by deleolajide** [comment] 2020-12-19 22:51
I can confirm the PR does work with Windows and  fixes the connection refused. I will tidy up the code, test on Linux and release 1.2.1 tomorrow 👍 thanks @naive924 

```
{"colibriClass":"ServerHello"}
2020.12.19 22:46:18 ProxyConnection - ProxyConnection - onMessage 
{"colibriClass":"ServerHello"}
2020.12.19 22:46:18 ProxyWebSocket -  : Delivered : 
{"colibriClass":"ServerHello"}
2020.12.19 22:46:18 ProxyConnection - ProxySocket onMessage 
{"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"dfcb1c1a"}
2020.12.19 22:46:18 ProxyConnection - ProxyConnection - onMessage 
{"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"dfcb1c1a"}

```

**Comment by gjaekel** [comment] 2020-12-19 23:20
@deleolajide: May test it on Linux using a local build as soon as you commit.

**Closed** 2020-12-19 23:51 UTC

**Comment by deleolajide** [comment] 2020-12-20 00:09
Confirmed that it works on Linux as well

```
2020.12.20 00:07:13 ProxyWebSocket - : onMessage : Received :
{"colibriClass":"ReceiverVideoConstraint","maxFrameHeight":2160}
2020.12.20 00:07:13 ProxyConnection - ProxyConnection - deliver
{"colibriClass":"ReceiverVideoConstraint","maxFrameHeight":2160}
2020.12.20 00:07:13 ProxyConnection - ProxySocket deliver:
{"colibriClass":"ReceiverVideoConstraint","maxFrameHeight":2160}
2020.12.20 00:07:13 ProxyConnection - ProxySocket onMessage
{"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"18ef0b20"}
2020.12.20 00:07:13 ProxyConnection - ProxySocket onMessage
{"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"18ef0b20"}
2020.12.20 00:07:13 ProxyConnection - ProxyConnection - onMessage
{"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"18ef0b20"}
2020.12.20 00:07:13 ProxyConnection - ProxyConnection - onMessage
{"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"18ef0b20"}
2020.12.20 00:07:13 ProxyWebSocket - : Delivered :
{"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"18ef0b20"}
2020.12.20 00:07:13 ProxyWebSocket - : Delivered :
{"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"18ef0b20"}
2020.12.20 00:07:13 org.apache.mina.filter.ssl.SslFilter - Session Server[15](SSL): Writing Message : WriteRequest: HeapBuffer[pos=0 lim=1413 cap=4096: 3C 69 71 20 69 64 3D 22 33 63 34 31 65 33 34 63...]
2020.12.20 00:07:13 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event MESSAGE_SENT to session 15
Queue : [MESSAGE_SENT, ]
```

**Comment by gjaekel** [comment] 2020-12-20 00:41
I also confirm!! 

In a session with three participants, the network flow for the `colibri-ws` no shows ongoing messages in both directions. At the clients, the focus indicator appear and is changing.

**Comment by gjaekel** [comment] 2020-12-20 09:38
[OFMeeting Network Diagramm](https://docs.google.com/presentation/d/1TbGRwKB56xjK29HiOlUCOyw-MNm9rkhMNnmypOxz7f0/edit?usp=sharing)

**Comment by deleolajide** [comment] 2020-12-20 11:41
Just one comment. The default JVB websocket data channel for colibri-ws is 8180

**Comment by gjaekel** [comment] 2020-12-20 11:44
work-in-progess :) With the choosen form of link, the graphic is live-updated.

**Comment by gjaekel** [comment] 2020-12-20 11:55
Added a [Wiki page](https://github.com/igniterealtime/openfire-pade-plugin/wiki/OFmeet-Network-Scheme)

**Comment by gjaekel** [comment] 2020-12-20 11:58
Anybody know what UDP/4096 is for?
```
root@evalfire0 ~ # netstat -tulpen | grep 12269
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      2059       874059013  12269/java          
tcp        0      0 0.0.0.0:8180            0.0.0.0:*               LISTEN      2059       874059008  12269/java          
udp        0      0 10.10.1.141:4096        0.0.0.0:*                           2059       874047806  12269/java          
udp        0      0 10.10.59.52:10000       0.0.0.0:*                           2059       874151649  12269/java          
udp        0      0 10.10.1.141:10000       0.0.0.0:*                           2059       874151648  12269/java  
```
